name: project_fda_mobile_app
description: A Flutter app with Firebase Auth and real-time location updates to Firebase Realtime Database.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.3
  cloud_firestore: ^5.5.1

  # Location
  geolocator: ^13.0.1

  # Background Services
  flutter_background_service: ^5.0.5
  workmanager: ^0.5.2

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
